---
title: "ADA Project Analysis"
author: "Scott Heimberger"
date: "2022-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
# load in required packages
pacman :: p_load(tidyverse, odds.n.ends, car, jtools, broom, multcomp, lmtest, table1, blorr, DiagrammeR)
```

```{r data loading}
# load in data
nhis <- read_csv('/Users/scottheimberger/Documents/Fall2022/Advanced_Data_Analysis/Project/adult21.csv')

# subset the data to only include necessary columns and omit incomplete cases
nhis_subset <- nhis %>%
  dplyr :: select(c(SHTCVD19_A, PHSTAT_A, HISPALLP_A, HICOV_A, SEX_A, EDUCP_A, AGEP_A, HLTHCOND_A)) %>%
  na.omit()
```

```{r data cleaning}
# rename variables
nhis_subset <- rename(nhis_subset, c("covid_vac" = "SHTCVD19_A",
                                     "health_status" = "PHSTAT_A",
                                     "race_ethnicity" = "HISPALLP_A",
                                     "health_insurance" = "HICOV_A",
                                     "sex" = "SEX_A",
                                     "education" = "EDUCP_A",
                                     "age" = "AGEP_A",
                                     "immunosuppression" = "HLTHCOND_A"))

# check data types of each variable
lapply(nhis_subset, class)

# recode variables
nhis_clean <- nhis_subset %>%
  mutate(covid_vac = case_when(covid_vac==2~0,
                               covid_vac==1~1)) %>%
  mutate(health_insurance = case_when(health_insurance==2~0,
                                      health_insurance==1~1)) %>%
  mutate(sex = case_when(sex==2~0,
                         sex==1~1)) %>%
  mutate(education = case_when(education<=2~0,
                               education==3 | education ==4 ~1,
                               education >=5 & education <=7 ~2,
                               education == 8 ~ 3,
                               education == 9 | education == 10~ 3)) %>%
  mutate(immunosuppression = case_when(immunosuppression==2~0,
                                       immunosuppression==1~1)) %>%
  mutate(health_status = case_when(health_status == 5~0,
                                   health_status == 4~1,
                                   health_status == 3~2,
                                   health_status == 2~3,
                                   health_status == 1~4)) %>%
  mutate(race_ethnicity = case_when(race_ethnicity == 1~0,
                                    race_ethnicity == 2~1,
                                    race_ethnicity == 3~2))
  
# recode variables to factor variables
nhis_clean$covid_vac = factor(nhis_clean$covid_vac, levels = c(0,1), labels = c("Unvaccinated", "Vaccinated"))

nhis_clean$health_insurance = factor(nhis_clean$health_insurance, levels = c(0,1), labels = c("Uninsured","Insured"))

nhis_clean$sex = factor(nhis_clean$sex, levels = c(0,1), labels = c("Female", "Male"))

nhis_clean$education = factor(nhis_clean$education, levels = c(0,1,2,3), labels = c("Less than High School", "High School or GED", "Some College or Associate's Degree", "Bachelor's Degree or Above"))

nhis_clean$immunosuppression = factor(nhis_clean$immunosuppression, levels = c(0,1), labels = c("No Immunosuppression", "Immunosuppressed"))

nhis_clean$health_status = factor(nhis_clean$health_status, levels = c(0,1,2,3,4), labels = c("Poor", "Fair", "Good", "Very Good", "Excellent"))

nhis_clean$race_ethnicity = factor(nhis_clean$race_ethnicity, levels = c(0,1,2), labels = c("Hispanic", "Non-Hispanic White", "Non-Hispanic Black"))

# filter out the new NA's created by the mutate functions and the unnecessary values (like "refused" responses) from the clean dataset. Also, filter out all race/ethnicity categories other than NH White, NH Black, and Hispanic due to sample sizes
nhis_clean <- nhis_clean %>%
  na.omit() %>%
  filter(age<97)
```

```{r linearity assumption checking} 
# Box Tidwell test
nhis_clean <- nhis_clean %>%
  mutate(age.times.logage = age * log(age))

model_BT <- glm(covid_vac ~ age + age.times.logage + health_status + health_insurance + race_ethnicity + sex + education + immunosuppression, data=nhis_clean, family="binomial") 

model_BT2 <- glm(covid_vac ~ age + age.times.logage, data=nhis_clean, family="binomial")

summary(model_BT)
summary(model_BT2)
# due to the significance of the interaction term, the linearity assumption is violated, and age should be categorized 
```

```{r}
# convert age from a numerical variable to a factor variable
nhis_clean <- nhis_clean %>%
  mutate(age_cat = case_when(age >= 18 & age < 45 ~ 0,
                             age >=45 & age < 65 ~ 1,
                             age >= 65 & age <85 ~ 2,
                             age>=85 ~ 2))

nhis_clean$age_cat = factor(nhis_clean$age_cat, levels = c(0,1,2), labels = c("18-44", "45-64", "65+"))
```

```{r modeling}
model_adjusted <- glm(covid_vac ~ health_status + health_insurance + race_ethnicity + sex + education + age_cat + immunosuppression, data = nhis_clean, family = "binomial")

model_unadjusted <- glm(covid_vac ~ health_status, data = nhis_clean, family = "binomial")

odds.n.ends(model_adjusted)
summary(model_adjusted)

odds.n.ends(model_unadjusted)
summary(model_unadjusted)
```

```{r multicollinearity}
# multicollinearity check
vif(model_adjusted)

summ(model_adjusted, vifs = TRUE)

# all VIF values are less than 1.5, indicating no issues with multicollinearity 
```

```{r influential observations}
model.data <- augment(model_adjusted) %>%  
  mutate(index = 1:n()) 

head(model.data)

cuttoff <- mean(model.data$.cooksd)*3

nhis_out <- model.data %>% 
  filter(.cooksd<cuttoff)

nrow(nhis_out)/nrow(nhis_clean) 
# just over 9% of observations were excluded based on cooks distance values 
# upon further examination, though observations that were excluded have higher cooks distance values, I cannot discern any other reason to exclude them. All of my predictor variables are categorical, so these excluded observations do not have unreasonable values for any predictors 
```

```{r modeling 2}
# rerun the model with influential observations excluded 
model2 <- glm(covid_vac ~ health_status + health_insurance + race_ethnicity + sex + education + age_cat + immunosuppression, data = nhis_out, family = "binomial")

summary(model2)

odds.n.ends(model2)
```

```{r}
# compare coefficients with and without influential observations
compareCoefs(model_adjusted, model2)
```

```{r}
# test for multicollinearity in model 2
vif(model2)

summ(model2, vifs = TRUE)
# all VIF values are less than 1.25, indicating no issues with multicollinearity 
```

```{r}
# testing for effect modification

# create a third model that includes an interaction term between insurance status and health status 
model3 <- glm(covid_vac ~ health_status + health_insurance + race_ethnicity + sex + education + age_cat + immunosuppression + health_status*health_insurance, data = nhis_out, family = "binomial")

summary(model3)
lrtest(model2, model3)
# the interaction is improving model fit 
# the interaction term is significant
```

```{r}
# due to the significant interaction, so I will now run models stratified by insurance status 

# create a subset including only those who are insured
nhis_insured <- nhis_clean %>%
  filter(health_insurance=="Insured")

# create a subset including only those who are uninsured and excluding those with a bachelor's and those age 65+
nhis_uninsured <- nhis_clean %>%
  filter(health_insurance=="Uninsured") %>%
  filter(education != "Bachelor's Degree or Above") %>%
  filter(age_cat != "65+") %>%
  filter(health_status != "Poor")

model_insured_adjusted <-  glm(covid_vac ~ health_status + race_ethnicity + sex + education + age_cat + immunosuppression, data = nhis_insured, family = "binomial")

model_insured_unadjusted <-  glm(covid_vac ~ health_status, data = nhis_insured, family = "binomial")

model_uninsured_adjusted <- glm(covid_vac ~ health_status + race_ethnicity + sex + education + age_cat + immunosuppression, data = nhis_uninsured, family = "binomial")

model_uninsured_unadjusted <- glm(covid_vac ~ health_status, data = nhis_uninsured, family = "binomial")

# examine both stratified models 
summary(model_insured_adjusted)
summary(model_uninsured_adjusted)
summary(model_insured_unadjusted)

odds.n.ends(model_insured_adjusted, predProbPlot=TRUE, rocPlot = TRUE)
odds.n.ends(model_insured_unadjusted)

odds.n.ends(model_uninsured_adjusted, predProbPlot=TRUE, rocPlot = TRUE)
odds.n.ends(model_uninsured_unadjusted)
```

```{r}
# examine influential observations for insured model
model_insured.data <- augment(model_insured_adjusted) %>%  
  mutate(index = 1:n()) 

cuttoff_insured <- mean(model_insured.data$.cooksd)*3

nhis_insured_out <- model_insured.data %>% 
  filter(.cooksd<cuttoff_insured)

nrow(nhis_insured_out)/nrow(nhis_insured) 
# # just under 10% of observations were excluded based on cooks distance values 
# upon further examination, though observations that were excluded have higher cooks distance values, I cannot discern any other reason to exclude them. All of my predictor variables are categorical, so these excluded observations do not have unreasonable values for any predictors 

# examine influential observations for uninsured model 
model_uninsured.data <- augment(model_uninsured_adjusted) %>%  
  mutate(index = 1:n()) 

cuttoff_uninsured <- mean(model_uninsured.data$.cooksd)*3

nhis_uninsured_out <- model_uninsured.data %>% 
  filter(.cooksd<cuttoff_uninsured)

nrow(nhis_uninsured_out)/nrow(nhis_uninsured) 
# # just under 2% of observations were excluded based on cooks distance values 
# upon further examination, though observations that were excluded have higher cooks distance values, I cannot discern any other reason to exclude them. All of my predictor variables are categorical, so these excluded observations do not have unreasonable values for any predictors 
```

```{r}
# goodness of fit tests 
blr_model_fit_stats(model_insured_adjusted)
blr_model_fit_stats(model_uninsured_adjusted)

blr_test_hosmer_lemeshow(model_insured_adjusted) # significant p-value indicates a bad fit
blr_test_hosmer_lemeshow(model_uninsured_adjusted) # p-value is not significant, indicating a better fit 
```

```{r}
# test for multicollinearity in both stratified models 
summ(model_insured, vifs = TRUE)
summ(model_uninsured, vifs = TRUE)
# all VIF values are below 1.5, incidcating no issues with multicollinearity 
```

```{r}
label(nhis_clean$race_ethnicity) <- "Race and Ethnicity"
label(nhis_clean$sex) <- "Sex"
label(nhis_clean$education) <- "Education Level"
label(nhis_clean$age_cat) <- "Age (years)"
label(nhis_clean$covid_vac) <- "COVID-19 Vaccination Status"
label(nhis_clean$health_insurance) <- "Health Insurance Status"
label(nhis_clean$health_status) <- "Perceived Health Status"

# table detailing demographics of study population
table1(~race_ethnicity + sex + education + age_cat + health_insurance + health_status + covid_vac, rowlabelhead = "Variable", overall = "Total", nhis_clean, topclass = "Rtable1-zebra Rtable1-times")
```

```{r}
# create figure 1 to demonstrate exclusions 
grViz("digraph flowchart {

      node [shape = rectangle, fontsize=12] 
      
      tab1 [label = '@@1'] 
      tab2 [label = '@@2'] 
      tab3 [label = '@@3'] 
      
      tab1 -> tab2 -> tab3 
}
      #This set of code provides the text in each rectangle box.
      [1]: 'Records received from NHIS n=29,482'
      [2]: 'Excluding 8,213 individuals with NA, Refused, Not Ascertained, or Do Not Know values for variables used in the analysis n=21,269'
      [3]: 'Excluding 1,853 individuals in Non-Hispanic Asian, Non-Hispanic AIAN, or Other groups n=19,416'
      ")
```

